
version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: music_booking
    environment:
      POSTGRES_DB: music_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Michael2006#
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: music_booking_keycloak
    environment:
      KEYCLOAK_ADMIN: michael
      KEYCLOAK_ADMIN_PASSWORD: Michael2006#
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - "8085:8080"
    depends_on:
      - postgres
    command: start-dev
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  postgres_data:
